### ISSUE TITLE
file.managed mode should be '0644' instead of 0644

### ISSUE THREAD

**Issue by Talkless** [saltstack-formulas/shorewall-formula#8]
Looking ant [YAML Idiosyncrasies](https://docs.saltstack.com/en/latest/topics/troubleshooting/yaml_idiosyncrasies.html#integers-are-parsed-as-integers) Salt documentation, 0644 will be interpreted as octal and  becomes 420.

[salt.states.file](https://docs.saltstack.com/en/latest/ref/states/all/salt.states.file.html) always use '0644' or 644 in their examples.

**Comment by wwentland** [comment]
It should indeed, good catch! I'd happily merge a PR if you would be interested in creating one. If not, let me know as well.

Which file and state does this concern, btw?

**Comment by Talkless** [comment]
I was thinking about PR, but it's such a small change I figured maybe creator could fix it right up :-)

**Comment by wwentland** [comment]
Everybody would create a PR so that it can be merged by someone else. We try to avoid direct pushes so that somebody else looks over the changes.

**Comment by Talkless** [comment]
OK I'll make PR this evening.

**Comment by Talkless** [comment]
Implemented in  [PR #10](https://github.com/saltstack-formulas/shorewall-formula/pull/10)
